# Generated by Django 4.2.30 on 2026-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_income_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('fun', 'Fun'), ('future', 'Future')], default='fixed', max_length=20),
        ),
    ]
