# Generated by Django 4.2.30 on 2026-06-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_expense_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
